# -*- coding: utf-8 -*-
"""Cat vs Dogs Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhYkh-t-ZjtobZ-ixuiA8c10LHZAWXVi
"""

mkdir -p ~/.kaggle && echo KGAT_8a0d0aa6f5bf2f22c4946689c3798f93 > ~/.kaggle/access_token && chmod 600 ~/.kaggle/access_token

import kagglehub

path = kagglehub.dataset_download(
    "salader/dogsvscats",
    output_dir="/content/data"
)
print("Path to dataset files:", path)

import tensorflow as tf
from tensorflow import keras
from keras import Sequential, layers
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, BatchNormalization,Dropout, GlobalAveragePooling2D

# generators to make images batch sized

test_data = keras.utils.image_dataset_from_directory(
    directory = '/content/data/train',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256,256)
)

validation_data = keras.utils.image_dataset_from_directory(
    directory = '/content/data/test',
    labels = 'inferred',
    label_mode = 'int',
    batch_size = 32,
    image_size = (256,256)
)

def process(image,label):
  image = tf.cast(image/256, tf.float32)
  return image,label

test_data = test_data.map(process)
validation_data = validation_data.map(process)

# CNN Model

model = Sequential([
    Conv2D(32, kernel_size=(3,3), padding='valid', activation='relu', input_shape=(256,256,3)),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2), strides=2,padding='valid'),

    Conv2D(64, kernel_size=(3,3), padding='valid', activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'),

    Conv2D(128, kernel_size=(3,3), padding='valid', activation='relu'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'),

    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.1),
    Dense(64, activation='relu'),
    Dropout(0.1),
    Dense(1,activation='sigmoid')
])

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(test_data, epochs= 10 ,validation_data = validation_data)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'], color='red',label='train')
plt.plot(history.history['val_accuracy'], color='blue',label='validation')
plt.legend()
plt.show()

import cv2

test_img = cv2.imread('/content/data/dog.jpg')

plt.imshow(test_img)

test_img.shape

test_img = cv2.resize(test_img,(256,256))

test_input = test_img.reshape((1,256,256,3))

model.predict(test_input)

