# -*- coding: utf-8 -*-
"""CNN Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ahq0yD2X2Aj60p7ToujLQrY0_0ku_Uyk
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.models import Sequential
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import SimpleRNN, Dense
import numpy as np
import pandas as pd

mnist = tf.keras.datasets.mnist
(X_train,y_train), (X_test,y_test) = mnist.load_data()

X_train, X_test = X_train / 255.0, X_test / 255.0

X_train = X_train[...,tf.newaxis]
X_test = X_test[...,tf.newaxis]

model = models.Sequential([
    layers.Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(54,(3,3),activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(54,activation='relu'),
    layers.Dense(10,activation='softmax')
])

model.summary()

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(X_train,y_train,epochs=3,validation_split=0.1)

loss, accuracy = model.evaluate(X_test,y_test)
print(f"Loss: {loss}")
print(f"Accuracy: {accuracy}")

df = pd.read_csv('module_157_data.csv')
df.head()

X = df.drop('target',axis=1).values
y = df['target'].values

X = X.reshape(X.shape[0],X.shape[1],1)
X

model = Sequential({
    SimpleRNN(32,input_shape=(10,1)),
    Dense(1,activation='sigmoid')
})
model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.fit(X,y,epochs=30,batch_size=42,validation_split=0.2)

loss, accuracy = model.evaluate(X,y)
print(f"Loss: {loss}")
accuracy = (accuracy)*100
print(f"Accuracy: {accuracy:.2f}")

