# -*- coding: utf-8 -*-
"""Decision Tree ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F7bAzDK7otSuNHe7cYCghRl9brXs6MJv
"""

import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=12,
    n_features=2,
    n_informative=2,
    n_redundant=0,
    random_state=42
)

feature_name = ["Feature_1","Feature_2"]
print("\nData-set of first 8 records")
for i in range(8):
  print(f" {feature_name[0]}={X[i,0]:.2f}"
        f"   {feature_name[1]}={X[i,1]:.2f}"
        f"Class={y[i]}")

tree = DecisionTreeClassifier(
    max_depth=2,
    criterion="gini",
    random_state=42
)
tree.fit(X,y)

print("\nDecision Tree Structure:")
print(export_text(tree,feature_names=feature_name))

print("\nFeature importance how each feature was used")
for name, importance in zip(feature_name,tree.feature_importances_):
  print(f"{name}: {importance:.3f}")

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

X, y = make_moons(n_samples=500, noise=0.25,random_state=42)

X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.3, random_state=42
)

depths = list(range(1,15))
train_acc=[]
test_acc=[]

for i in depths:
  model = DecisionTreeClassifier(max_depth=i,random_state=42)
  model.fit(X_train,y_train)
  train_pred=model.predict(X_train)
  test_pred = model.predict(X_test)

  train_acc.append(accuracy_score(y_train,train_pred))
  test_acc.append(accuracy_score(y_test,test_pred))

test_acc

plt.figure(figsize=(10,6))
plt.plot(depths,train_acc,label="Training Accuracy")
plt.plot(depths,test_acc,label="Testing Accuracy")
plt.title("Training & Testing Accuracy Analysis")
plt.xlabel("Depths")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

best_depth = depths[np.argmax(test_acc)]
print(f"The best depth based on test accuracy is depth: {best_depth}")

from sklearn.datasets import load_iris
from sklearn.tree import plot_tree
from sklearn.metrics import classification_report, confusion_matrix

data = load_iris()
X = data.data
y= data.target
feature_names = data.feature_names
class_names = data.target_names

X_train, X_test, y_train, y_test = train_test_split(
    X,y, test_size=0.3,random_state=42,stratify=y
)
y_test

model = DecisionTreeClassifier(
    max_depth=3,
    criterion="entropy",
    random_state=42
)
model.fit(X_train,y_train)

plt.figure(figsize=(10,6))
plot_tree(
    model,
    feature_names=feature_names,
    class_names=class_names,
    filled=True,
    rounded=True,
)
plt.title("Decision Tree Visualization (IRIS Data)")
plt.tight_layout()
plt.show()

y_pred = model.predict(X_test)
print("\n====Model Accuracy=====")
print(f"Accuracy: {accuracy_score(y_test,y_pred):.3f}\n")
print("====Confusion Matrix=======")
print(f"\n{confusion_matrix(y_test,y_pred)}\n")
print("========Classification Report=======")
print(f"{classification_report(y_test,y_pred,target_names=class_names)}")

