# -*- coding: utf-8 -*-
"""Exercise 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N7nJU52Yc0lL7qv3LnYPbI3JMRHw9_uQ
"""

import numpy as np
import pandas as pd

df = pd.read_csv('titanic.csv')
df.shape

df.head(7)

"""**Task 2:**"""

df.describe()

df.info()

print(f"Unique values  : {df['Sex'].unique()}")
print(f"Number of unique: {df['Sex'].nunique()}")

print(f'Passenger Class: {df['Pclass'].unique()}')
print(f'Number of unique: {df['Pclass'].nunique()}')

"""**Task 3**"""

print("Missing Values Accross All Columns: ",df.isnull().sum())

df['Age'] = df['Age'].fillna(df['Age']).median()
df['Cabin'] = df['Cabin'].fillna('Unknown')

df['Fare'] = df['Fare'].fillna(df['Fare']).median()

print("After Filling missing values: ",df.isnull().sum())

"""**Task 4**"""

from  sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder, StandardScaler

df.columns

target = 'Survived'
features = ['Pclass','Sex','Age','SibSp','Parch','Fare','Cabin','Embarked']

print(f"Target Variable: {target}")
print(f"Features: {features}")

df['Sex'] = LabelEncoder().fit_transform(df['Sex'])
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])

X = features
y = target

X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size=0.2,random_state=42
)

df['Cabin'] = LabelEncoder().fit_transform(df['Cabin'])

X = df[features]
y = df[target]

X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size=0.2,random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = SVC(kernel='rbf', random_state=42)
model.fit(X_train,y_train)

y_pred = model.predict(X_test)
print(f"\nAccuracy Score: {accuracy_score(y_test,y_pred)}")
print(f"\Confusion Matrix:\n {confusion_matrix(y_test,y_pred)}")
print(f"\nClassification Report\n: {classification_report(y_test,y_pred)}")

import seaborn as sns

plt.figure(figsize=(10,6))
sns.catplot(x='Pclass', hue='Survived', col='Sex', data=df, kind='count')
plt.suptitle('Survival by Gender and Passenger Class', y=1.02)
plt.show()

plt.figure(figsize=(10,6))
plt.hist(df['Fare'],bins=30,edgecolor='k')
plt.xlabel("Fare")
plt.ylabel("Frequency")
plt.title("Fare Distribution")
plt.show()

plt.figure(figsize=(10,6))
sns.countplot(x='Sex', hue='Survived', data=df)
plt.title('Survival by Gender')
plt.show()