# -*- coding: utf-8 -*-
"""Fraud Detection Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cD2emRRY6Khce5jQj0_ncwsLr5jCxDi-
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('AIML Dataset.csv')
df.head()

"""EDA and Quick Checks"""

print("Shape ",df.shape)
print("dTypes: ",df.dtypes)
df.isnull().sum()
print(df['isFraud'].value_counts())
print("Fraud Ratio: ",df["isFraud"].median())

df['isFlaggedFraud'].value_counts()

df.isnull().sum()

df['type'].value_counts().plot(kind="bar",title="Transcation types")
plt.xlabel("Transactions")
plt.ylabel("Counts")
plt.show()

#checking fraud rates by type

fraud_by_type = df.groupby('type')['isFraud'].mean().sort_values(ascending=False)
fraud_by_type.plot(kind='bar',color='salmon',title='Fraud Rate by Transaction Type')
plt.xlabel("Transaction Type")
plt.ylabel('Fraud Rate')
plt.show()

# Cheking amount hist

df['amount'].describe().astype(int)

sns.histplot(np.log1p(df['amount']),bins=100,color='green',kde=True)
plt.title("Amount Distribution")
plt.xlabel("Log Amount")
plt.ylabel("Frequency")
plt.show()

sns.boxplot(data= df[df['amount'] < 50000],x='isFraud',y='amount')
plt.title("Amount Distribution by Fraud under 50k")
plt.show()

df.columns

df['balanceDiffOrg'] = df["oldbalanceOrg"] - df["newbalanceOrig"]
df['balanceDiffDest'] = df["oldbalanceDest"] - df["newbalanceDest"]

df.drop(columns='step',inplace=True)

df.head(2)

top_senders = df['nameOrig'].value_counts().head(10)
top_senders

top_receivers = df['nameDest'].value_counts().head(10)

fraud_users = df[df['isFraud']==1]['nameOrig'].value_counts().head(10)

fraud_users

fraud_types = df[df['type'].isin(["TRANSFER","CASH_OUT"])]
fraud_types.value_counts()

sns.countplot(data=fraud_types,x='type',hue='isFraud')
plt.title("Fraud Distribution in TRANSFER & CASH_OUT")
plt.show()

from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

df.head()

df_model = df.drop(['nameOrig','nameDest','isFlaggedFraud'],axis=1)

df_model.head()

categorical = ["type"]
numeric = ["amount","oldbalanceOrg","newbalanceOrig","oldbalanceDest","newbalanceDest"]

y = df_model['isFraud']
X = df_model.drop('isFraud',axis=1)

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3,random_state=42,stratify=y
)

preprocessor = ColumnTransformer(
    transformers=[
        ("num",StandardScaler(),numeric),
        ("cat",OneHotEncoder(drop="first"),categorical)
    ],
    remainder="drop"
)

pipeline = Pipeline([
    ("prep",preprocessor),
    ("clf",LogisticRegression(class_weight="balanced",max_iter=1000))
])

pipeline.fit(X_train,y_train)

y_pred = pipeline.predict(X_test)

print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))
print("Classification Report: \n",classification_report(y_test,y_pred))