# -*- coding: utf-8 -*-
"""Google seach analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12uzm1GzxE4Tdw5233_SXG--wLWo98fuO
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
from pytrends.request import TrendReq

"""**Creating Keyword which can be changed**"""

pytrends = TrendReq(hl='en-US',tz=360)
keyword = "Cristiano Ronaldo"

pytrends.build_payload([keyword], cat=0, timeframe='today 12-m',geo='',gprop='')

"""**Top 15 countries where this keywords is searched the most and also its visual representation**"""

region_data = pytrends.interest_by_region()
region_data = region_data.sort_values(by=keyword,ascending=False).head(15)
region_data[keyword]

plt.figure(figsize=(10,6))
sns.barplot(x=region_data[keyword], y=region_data.index,palette='rocket')
plt.title(f"Top 15 countries searching for {keyword}")
plt.xlabel("Number of Searches")
plt.ylabel("Countries Name")
plt.show()

"""**World Map**"""

region_data = region_data.reset_index()
fig = px.choropleth(
    region_data,
    locations='geoName',
    locationmode='country names',
    color=keyword,
    hover_name='geoName',
    title=f"Search Interest For {keyword} by Country"
)
fig.show()

"""**Time Wise Interest**"""

time_df = pytrends.interest_over_time()
plt.figure(figsize=(10,6))
plt.plot(time_df.index,time_df[keyword], marker='o', color='purple')
plt.title(f"Interest Over Time For {keyword}")
plt.xlabel("Date")
plt.ylabel("Interest")
plt.grid(True)
plt.show()

"""**Multiple / Related Keywords and Plot Graph**"""

kw_list = ["Erling Haaland","Jude Bellingham", "Lamine Yamal","Kylian Mbappe"]
pytrends.build_payload(kw_list,cat=0,geo='',timeframe='today 12-m',gprop='')

compare_df = pytrends.interest_over_time()

plt.figure(figsize=(10,6))
for kw in kw_list:
  plt.plot(compare_df.index,compare_df[kw],marker='o',label=kw)
plt.title(f"Interest Over Time For Multiple Keywords")
plt.xlabel("Date")
plt.ylabel("Interest")
plt.tight_layout()
plt.legend()
plt.grid(True)
plt.show()