# -*- coding: utf-8 -*-
"""K Means Cluster.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKQER-nu-vGyYliN8Jn_t-j3_vDrTcMJ
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris, load_wine
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score

iris = load_iris()
X = iris.data

print("Data set Shape: ",X.shape)

kmeans = KMeans(n_clusters=3,init="k-means++",random_state=42,n_init=10)
kmeans.fit(X)

print("Cluster centers \n",kmeans.cluster_centers_)
print("First 10 Cluster Labels:",kmeans.labels_[:10])

"""**New Program**"""

wine = load_wine()
X = wine.data

print("Data set Shape:",X.shape)

features_names = wine.feature_names

df = pd.DataFrame(X,columns=features_names)
df.head()

selected_features = ['alcohol','malic_acid']
X_selected = df[selected_features].values
print("Selected Features: ",selected_features)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_selected)

inertia_value = []
k_range = range(1,11)

for k in k_range:
  kmeans = KMeans(n_clusters=k,init="k-means++",random_state=42,n_init=10)
  kmeans.fit(X_scaled)
  inertia_value.append(kmeans.inertia_)

plt.figure(figsize=(10,6))
plt.plot(k_range,inertia_value,marker='o')
plt.title("Elbow Method For Optimal k")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.show()

kmeans = KMeans(n_clusters=3,init="k-means++",random_state=42,n_init=10)
clusters = kmeans.fit_predict(X_scaled)
df['Cluster'] = clusters

print("\n Cluster Centers")
print(kmeans.cluster_centers_)

sil_score = silhouette_score(X_scaled,clusters)
print(sil_score)

