# -*- coding: utf-8 -*-
"""KNN & Naive Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-uAVY9L7PzJG0Z12YTb8WERdcM7oz12
"""

from sklearn.datasets import load_digits
from  sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB
import numpy as np
import pandas as pd

data = load_digits()
X = data.data
y = data.target

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42,stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Traning Samples: ",X_train.shape[0])
print("Features Samples: ",X_train.shape[1])

knn = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
knn.fit(X_train,y_train)

y_pred = knn.predict(X_test)

print("Accuracy: ",accuracy_score(y_test,y_pred))
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))
print("Classification Report: \n",classification_report(y_test,y_pred))

data_cancer = load_breast_cancer()
X = data_cancer.data
y = data_cancer.target

df = pd.DataFrame(X, columns=data_cancer.feature_names)
df['target'] = y

print("DataSet Shape: ",df.shape)
print("\nFirst 5 rows of dataset:\n")
df.head()

print("Target Classes",data_cancer.target_names)
print("\nTarget Clasess Distrubution",df['target'].value_counts())

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.25,random_state=42,stratify=y
)

print("Train Data Size",X_train.shape)
print("Test Data Size",X_test.shape)

nb_model = GaussianNB()
nb_model.fit(X_train,y_train)

y_pred = nb_model.predict(X_test)

print("Accuracy Score: ",accuracy_score(y_test,y_pred))
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))
print("Classification Report: \n",classification_report(y_test,y_pred))