# -*- coding: utf-8 -*-
"""Linear Regression Manually.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wIZB8ybvZJCpkksTKY4Gve398P2EcZpk
"""

import numpy as np

learning_rate = 0.01
epochs =5
X = np.array([1,2,3,4,5])
Y = np.array([3,4,2,5,4])

m,b = 0.0, 0.0
n = len(X)

for i in range(epochs):
    Y_pred = m*X + b
    cost = ((Y_pred - Y) **2).mean()
    derivative_m = (-2/n) * sum(X * (Y - Y_pred))
    derivative_b = (-2/n) * sum(Y - Y_pred)
    m-= learning_rate * derivative_m
    b-= learning_rate * derivative_b
    print(f"Epoch: {i+1}/{epochs}, Cost: {cost}, m: {m}, b:{b}")

from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt

X = np.array([[1],[2],[3],[4],[5]])
Y = np.array([3,6,7,8,11])

plt.figure(figsize=(10,5))
plt.scatter(X,Y)
plt.title("Scatter Plot Before Linear Regression")
plt.show()

model = LinearRegression()
model.fit(X,Y)
Y_pred = model.predict(X)
print(f"Predicted Values: {Y_pred}")

plt.figure(figsize=(10,6))
plt.scatter(X,Y, color='blue', label="Original Data")
plt.plot(X,Y_pred,color='red', label= "Best Fit Line")
plt.title("Scatter Plot After Linear Regression")
plt.xlabel("X Values")
plt.ylabel("Y Values")
plt.legend()
plt.show()

m = model.coef_
b = model.intercept_
print(f"m: {m}, b: {b}")