# -*- coding: utf-8 -*-
"""NetFlix Data Analysis - Pre-processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n68pFOYSfu9PYeRb6yvSx8ZVgjLtC6jp
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("mymoviedb.csv",lineterminator="\n")
df.info()

df.duplicated().sum()

# Exploration Summary

# 1. We have 9287 rows and 8 cols
# 2. We dono thave any null values
# 3. We have to convert Release_date to date time type and get year only in dataframe
# 4. We have to clean Genre cols to remove white spaces
# 5. Remove unwanted columns like poster_url, overview, original_langugae
# 6. There are no duplicates in our dataset
# 7. no outliners present in data set
# 8. Vote_average to be better categorized

df['Release_Date'] = pd.to_datetime(df['Release_Date'])
print(df["Release_Date"].dtype)

# df["Release_Date"] = df["Release_Date"].dt.year
# df["Release_Date"].dtypes

# Remove unwanted columns

cols = ["Overview","Original_Language","Poster_Url"]
df.drop(cols, axis=1, inplace=True)

# # Categorizing Vote_average columns

# # We would cut Vote_average columns and set it into four categories, Popular, Average, below_avg,
# not_popular, to describe more it using categorize_col() function

def categorize_col(df,col,labels):
  edges = [
      df[col].describe()['min'],
      df[col].describe()['25%'],
      df[col].describe()['50%'],
      df[col].describe()['75%'],
      df[col].describe()['max']
  ]
  df[col] = pd.cut(df[col],edges,labels=labels,duplicates = 'drop')
  return df

labels = ['not_popular','below_avg','average','popular']
categorize_col(df,'Vote_Average',labels)

df['Vote_Average'].value_counts()

df.isna().sum()

"""**Exploding genre data into new seprate lines**"""

df['Genre'] = df['Genre'].str.split(', ')
df = df.explode('Genre').reset_index(drop=True)
df.head()

"""**Casting columns into categories**"""

df['Genre'] = df['Genre'].astype('category')
df["Genre"].dtypes

df.nunique()
df.head()

"""**Data Visualization**"""

sns.set_style('whitegrid')

"""**Most Frequent Genre Realeased on Netflix\**"""

sns.catplot(y='Genre', data=df, kind='count',color="#7F00FF", order=df['Genre'].value_counts().index)
plt.title("Most Frequent Genre Realeased on Netflix")
plt.show()

"""**Highest Votes in Votes Average Column**"""

sns.catplot(y='Vote_Average',data=df,kind='count',order=df['Vote_Average'].value_counts().index,color="#7F00FF")
plt.title("Highest Votes in Votes Average Column")
plt.show()

"""**Which movie got highest popularity and what is the Genre:**"""

def get_popular_movie():
  popular_movie = df[df['Popularity'] == df['Popularity'].max()]
  print(popular_movie[['Title','Genre']])

get_popular_movie()

"""**Which movie got lowest popularity and what is the Genre:**"""

def get_popular_movie():
  popular_movie = df[df['Popularity'] == df['Popularity'].min()]
  print(popular_movie[['Title','Genre']])

get_popular_movie()

"""**In which year most moviews were flimed**"""

df['Release_Date'].hist()
plt.title("Release Date Distribution")
plt.show()

"""# Conclusion

1. Most popular category is Drama
2. Highest Vote_Average is in Average Column
3. Most popular movie is **Spider-man No way home** in **"Action","Adenvture" and "Science Ficton"** Genre
4. Lest popular movie are **The United States vs. Billie** and **Threads** in **"Music","Drama","History", "Science Fiction" and "War"** Genre
5. Most numbers of movies were filmmed in 2020 as per data
"""

