# -*- coding: utf-8 -*-
"""OpenCV Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fr3CKF9GyCaATXQYaVYIoRvBy8xZCi7n
"""

import cv2

image = cv2.imread('/content/images.jpg')

if image is None:
  print("Image doesnot exist")
  exit()
else:
  print("Image loaded successfully")

gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
gray

blur = cv2.GaussianBlur(gray,(3,3),0)
blur

median = cv2.medianBlur(gray,5)
median

edges = cv2.Canny(gray,100,200)
edges

resized = cv2.resize(image, (400,300))
resized

height, width = image.shape[:2]
center = (width//2 , height//2)

rotation_matrix = cv2.getRotationMatrix2D(center,45,1)
rotated = cv2.warpAffine(image,rotation_matrix,(width,height))
rotated

flipped = cv2.flip(image,1)
flipped

cv2.imwrite("edges_output.jpg",edges)

