# -*- coding: utf-8 -*-
"""PCA - Principal Component Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2RQaq-yR2xlD5KjYTkyDSYsL8a-qvAC
"""

import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_breast_cancer
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt

data = load_breast_cancer()
X = data.data
y = data.target
feature_names = data.feature_names

X

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
X_pca

print("Original Data", X.shape)
print("Reduced Data", X_pca.shape)

print("Explained Variance Ratio",pca.explained_variance_ratio_)

print("Total Variance Preserved",np.sum(pca.explained_variance_ratio_))

plt.figure(figsize=(10,6))
plt.scatter(X_pca[:,0],X_pca[:,1],c=y)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("PCA of Breast Cancer Dataset")
plt.show()
#

"""**PCA on Digits Data**"""

data = load_digits()
X = data.data
y = data.target
feature_names = data.feature_names

X

X_scaled = scaler.fit_transform(X)
X_scaled

X_pca = pca.fit_transform(X)
X_pca

print("Original Data",X.shape)
print("Reduced Data",X_pca.shape)

print("Explained Variance Ratio",pca.explained_variance_ratio_)

print("Total Explained Variance Ratio",np.sum(pca.explained_variance_ratio_))

plt.figure(figsize=(10,6))
plt.scatter(X_pca[:,0], X_pca[:,1],c=y)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Componenet 2")
plt.title("PCA of Digits Dataaset")
plt.show()

