# -*- coding: utf-8 -*-
"""RAG Implementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1llNij4HrArg5rupMIxrnDinthDSjuSC0
"""

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.document_loaders import TextLoader

"""**Generating Data Chunks**"""

content = "LangChain is an open-source framework designed to simplify the creation of applications using large language models. It acts as a powerful orchestrator that connects these models with external data sources, computation engines, and software tools. By providing a modular architecture, it allows developers to easily chain together different components like prompts, models, and databases into a seamless workflow. This enables the development of advanced context-aware systems, such as intelligent chatbots, automated document analysis tools, and autonomous agents that can reason and take actions based on real-time information. RAG stands for Retrieval-Augmented Generation. It is an artificial intelligence (AI) technique used to improve the accuracy and reliability of large language models (LLMs) by fetching facts from external data sources before generating a response."

with open('langchain-intro.txt','w') as file:
  file.write(content)

loader = TextLoader('langchain-intro.txt',encoding='utf-8')
documents = loader.load()
print(f"Document Loaded {len(documents)} documents")

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size = 199,
    chunk_overlap = 20,
    length_function = len,
    separators = ["\n\n", "\n", " ",""]
)
splits = text_splitter.split_documents(documents)

embeddings_function = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

db = FAISS.from_documents(
    documents = splits,
    embedding = embeddings_function
)

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM,pipeline
from langchain_huggingface import HuggingFacePipeline
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableLambda

model_id = 'Qwen/Qwen2-0.5B-Instruct'

print("Loading model ..." ,model_id)
tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    torch_dtype="auto",
    device_map='auto'
)

pipeline = pipeline(
    "text-generation",
    model = model,
    tokenizer = tokenizer,
    max_new_tokens = 128,
    temperature = 0.1,
    do_sample = True
)

raw_llm = HuggingFacePipeline(pipeline = pipeline)



"""**Setting up LLM Pipeline**"""

def format_qwen(input_dict):
    messages = [
        {
            "role": "system",
            "content": (
                "You are a helpful AI assistant which answers questions based on "
                "the provided context. Do not use any external knowledge or make "
                "up any content. If the answer is not in the context, just reply: "
                "'I don't know the answer to this query based on your provided context.' "
                "Always answer your query in the following format: "
                "'Answer': 'Your answer'"
            )
        },
        {
            "role": "user",
            "content": f"""
Context:

{input_dict['context']}

Question:

{input_dict['question']}
"""
        }
    ]

    formatted_prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True
    )

    return formatted_prompt

def generate_with_qwen(formatted_prompt):
    response = raw_llm.invoke(formatted_prompt)

    generated = response.split(formatted_prompt)[-1].strip()

    if generated.startswith("Answer:"):
        generated = generated.split("Answer:", 1)[-1].strip()

    return generated

llm_with_format = (
    RunnableLambda(format_qwen)
    | RunnableLambda(generate_with_qwen)
    | StrOutputParser()
)

print("LLM Setup Complete")

"""**Building RAG**"""

from langchain_core.runnables import RunnablePassthrough
from langchain_classic.chains import create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate

retriever = db.as_retriever(search_kwargs={"k":2})

rag_chain = (
    {
        "context": retriever | (lambda docs: "\n\n".join(doc.page_content for doc in docs)),
        "question": RunnablePassthrough()
    } | llm_with_format
)

question = "What does RAG stands for"
print(f"Question: {question}")

response = rag_chain.invoke(question)
print(response)

print('--------------')
context = retriever.invoke(question)
for doc in context:
  print(doc.page_content)