# -*- coding: utf-8 -*-
"""RandomForestImplementation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-KChFnwZL7P3OjzKWqM0hznDUn4UUH8-
"""

import numpy as np
from sklearn.datasets import load_iris
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

data = load_iris()
X = data.data
y = data.target
feature_names = data.feature_names

X_train,X_test,y_train,y_test = train_test_split(
    X,y, test_size=0.3,random_state=42,stratify=y
)

rf = RandomForestClassifier(n_estimators=50,random_state=42,bootstrap=(True),n_jobs=-1)

rf.fit(X_train,y_train)

y_pred = rf.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test,y_pred):.3f}\n")

data2 = load_breast_cancer()
X = data2.data
y = data2.target
feature_names = data2.feature_names

X_train, X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3,random_state=42,stratify=y
)

rf_new = RandomForestClassifier(
    n_estimators=100,random_state=42,bootstrap=(True),n_jobs=-1,criterion="entropy"
)

rf_new.fit(X_train,y_train)

y_pred = rf_new.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test,y_pred):.3f}\n")
print(f"\nConfusion Matrix:\n{confusion_matrix(y_test,y_pred)}")
print(f"\nClassification Records:\n{classification_report(y_test,y_pred)}")

data2 = load_breast_cancer()
X = data2.data
y = data2.target
feature_names = data2.feature_names

X_train, X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.3,random_state=42,stratify=y
)

param_grid = {
    "n_estimators": [20,50,100,200],
    "max_depth": [None,5,10,20],
    "min_samples_split":[2,5,10,1],
    "min_samples_leaf":[1,2,3,4]
}

rf_new = RandomForestClassifier(random_state=42,n_jobs=-1)

grid = GridSearchCV (
    estimator=rf_new,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
grid.fit(X_train,y_train)

best_model = grid.best_estimator_
y_pred = best_model.predict(X_test)
print("\n=== Best Parameter Found ===")
for k,v in grid.best_params_.items():
  print(f"{k}: {v}")

print(f"\n Accuracy: {accuracy_score(y_test,y_pred)}")

