# -*- coding: utf-8 -*-
"""Uber Data Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yuKLzcDsXxotuOI-1TD6G8NZh7MYKxC
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from datetime import datetime

df = pd.read_csv("UberDataset.csv")
df.info()

"""**Data Pre-Processing**"""

df['PURPOSE'].fillna("NOT", inplace=True)
df.head()

df['START_DATE'] = pd.to_datetime(df['START_DATE'], errors='coerce')
df['END_DATE'] = pd.to_datetime(df['END_DATE'], errors='coerce')

df['Date'] = pd.DatetimeIndex(df["START_DATE"]).date
df['Time'] = pd.DatetimeIndex(df['START_DATE']).hour
df.head()

df['Day-Night'] = pd.cut(x=df['Time'],bins=[0,10,15,19,24],labels=['Morning','Afternoon','Evening','Night'])

"""**Cateogry and Purpose for which most rides are booked**"""

plt.figure(figsize=(20,5))
plt.subplot(1,2,1)
sns.countplot(df['CATEGORY'])

plt.subplot(1,2,2)
sns.countplot(df['PURPOSE'])
plt.tight_layout()

"""**For what time category book the most**"""

plt.figure(figsize=(20,5))
sns.countplot(df['Day-Night'])

df['Month'] = pd.DatetimeIndex(df['START_DATE']).month
month_labels = {
    1.0:'Jan',
    2.0:'Feb',
    3.0:'Mar',
    4.0:'Apr',
    5.0:'May',
    6.0:'Jun',
    7.0:'Jul',
    8.0:'Aug',
    9.0:'Sep',
    10.0:'Oct',
    11.0:'Nov',
    12.0:'Dec'
}

df['Month'] = df.Month.map(month_labels)
mon = df.Month.value_counts(sort=False)

df_month = pd.DataFrame(
    {
        "Months": mon.values,
        "Value Count": df.groupby('Month', sort=False)['MILES'].max()
    }
)

p = sns.lineplot(data=df_month)
p.set(xlabel="Months",ylabel="Value Counts")

"""**Which weekday have most or less rides**"""

df['WeekDay'] = pd.DatetimeIndex(df['START_DATE']).weekday
week_label = {
    0:"Monday",1:"Tuesday,",2:"Wednesday",3:"Thursday",4:"Friday",5:"Saturday",6:"Sunday"
}
df['WeekDay'] = df['WeekDay'].map(week_label)

day_label = df['WeekDay'].value_counts(sort=False)

plt.figure(figsize=(10,5))
sns.barplot(x=day_label.index,y=day_label)
plt.xlabel("DAY")
plt.ylabel("COUNT")
plt.title("RIDES BY WEEK-DAY")
plt.show()

"""**For Mostly How Many Miles Rides are being Booked\**"""

filtered = df[df['MILES'] < 40]

plt.figure(figsize=(10,5))
sns.boxplot(x=filtered['MILES'])
plt.title("For Mostly How Many Miles Rides are being Booked")

plt.show()